---
- name: Stop production services
  hosts: all
  become: true
  vars:
    env_file: "{{ project_dir }}/.env"

  tasks:

    # 🔹 Debug project directory
    - name: Show project directory
      debug:
        msg: "Stopping services in project directory: {{ project_dir }}"

    # 🔹 Check if .env exists
    - name: Check if .env file exists
      stat:
        path: "{{ env_file }}"
      register: env_file_stat

    - name: Show .env file status
      debug:
        var: env_file_stat

    # 🔹 Stop services
    - name: Stop docker-compose services
      ansible.builtin.shell: |
        set -a
        source {{ env_file }}
        set +a
        doppler run -- docker-compose stop
      args:
        chdir: "{{ project_dir }}"
      register: stop_result
      ignore_errors: yes

    - name: Show stop service result
      debug:
        var: stop_result
